# Jets::Config.project_namespace is special value results in using the project namespace. Example :
# table_namespace: Jets::Config.project_namespace
# This is the default value.

# More examples:
# table_namespace: dev
# table_namespace: dev-1
# table_namespace: proj-dev-1
# table_namespace: stag
# table_namespace: prod

development:
  table_namespace: proj # do not include the env
  endpoint: http://localhost:8000

production:
  table_namespace: proj # do not include the env
