default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'demo_dev' %>
  username: <%= ENV['DB_USER'] || 'tung' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  url: "postgresql://deployuser:deployuser@test-db.ckm5uyz7uk58.us-east-1.rds.amazonaws.com/hello?pool=5"

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  # TODO: remove hardcode of test database url
  url: "postgresql://deployuser:deployuser@test-db.ckm5uyz7uk58.us-east-1.rds.amazonaws.com/hello?pool=5"
